# image will be published to ghcr.io/<user>/<name>
name: vanguard
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/che/zed/repo/fedora-%OS_VERSION%/che-zed-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/dusansimic/themes/repo/fedora-%OS_VERSION%/dusansimic-themes-fedora-%OS_VERSION%.repo
    install:
      - btop
      - starship
      - fish
      - zed
      - qemu
      - qemu-kvm
      - adw-gtk3-theme
      - morewaita-icon-theme
      - grc
      - exa
      - bat
    remove:
      - firefox
      - firefox-langpacks
      - htop
      - nvtop
      - yelp
      - gnome-system-monitor
      - gnome-tour

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - io.github.zen_browser.zen
        - org.mozilla.Thunderbird
        - com.mattjakeman.ExtensionManager
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog
  - type: gnome-extensions
    install:
      - Blur my Shell
      - AppIndicator and KStatusNotifierItem Support
    uninstall:
      #- GSConnect # Uninstall step here should be used only for the extensions
      # which are not installed through OS package manager in the base image,
      # like extensions installed from gnome-extensions module
  - type: bling
    install:
      - ublue-update # https://github.com/ublue-os/ublue-update
      - dconf-update-service # a service unit that updates the dconf db on boot
  - type: gschema-overrides
    include:
      - general.gschema.override
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
