alias ls='eza -la'
alias cat='bat --paging=never'
alias glow='glow --pager'
alias ip='ip --color --brief'
alias less='bat'
alias dmesg='dmesg --human --color=always'
alias tree='eza --tree'
alias reboot='systemctl reboot'
alias shutdown='systemctl poweroff'
alias gc='git add . && git commit -m'
alias gp='git push'
